# trigger the pipeline on any team branch
trigger:
  branches:
    include:
      - team4

pr:
  branches:
    include:
      - team4

# deployment tokens are stored in the variable group pacman-vars
variables:
- group: pacman-vars

- name: MY_APP_LOCATION
  value: "/"  # apps source files are in the root

- name: MY_API_LOCATION  
  value: ""   # no api used

- name: MY_APP_ARTIFACT_LOCATION
  value: "/"  # output artifacts will be placed in the root

stages:
- stage: BuildAndDeploy
  displayName: "Build and Deploy"
  jobs:
  - job: BuildDeploy
    displayName: "Build and Deploy Job"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: true

   
    - task: AzureStaticWebApp@0
      displayName: "Deploy to Azure Static Web Apps"
      inputs:
        app_location: '$(MY_APP_LOCATION)'
        api_location: '$(MY_API_LOCATION)'
        output_location: '$(MY_APP_ARTIFACT_LOCATION)'
        azure_static_web_apps_api_token: '$(AZURE_TOKEN)'
